### PR TITLE
Email Address - Markdown Link

### PR DESCRIPTION
**Pull request by vijay-jaisankar**
In this PR, the following functionalities have been added
- mailto link in `CODE_OF_CONDUCT.md`

### CODE REVIEW

**Review by kb-s — CHANGES_REQUESTED** [review]
**mailto --> mail to**

**Comment by vijay-jaisankar** [comment]
ref: https://github.com/AccessibleForAll/Support/pull/19#pullrequestreview-1018794338
Thanks for the feedback! 

The `mailto` clause is a special clause that opens up the default mail program, which is why there is no space in the link. (ref: https://css-tricks.com/snippets/html/mailto-links/) If we replace `mailto` with `mail to`, the link would be invalid and hence defeating the purpose of the PR.

~Vijay

**Comment by kb-s** [comment]
Thanks @vijay-jaisankar 👍

**Review by emmalearnscode — APPROVED** [review]
This looks great, thank you!

**Pull request merged**
